name: fuga_felina
description: "Um emocionante jogo de labirinto estilo arcade onde você ajuda um gatinho a encontrar seu novelo de lã no escuro."
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Biblioteca que cria os ícones nativos automaticamente
  flutter_launcher_icons: ^0.13.1 

# Configuração do gerador automático de ícones
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png" # Caminho da imagem do ícone do gatinho
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # Configuração dos Assets de Textura e Áudio
  assets:
    - assets/images/logo.png
    - assets/images/chao.png
    - assets/images/parede.png
    - assets/images/meta.png