// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8nZUpgH3XToww0lczaDuzTDyH802Ffe8',
    appId: '1:305345322623:web:1d351f4ad3889de9e8a94a',
    messagingSenderId: '305345322623',
    projectId: 'comunityler',
    authDomain: 'comunityler.firebaseapp.com',
    storageBucket: 'comunityler.firebasestorage.app',
    measurementId: 'G-216G684N77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByKWr92bX54T5TYEDmVdJlx_X_tWemyYs',
    appId: '1:305345322623:android:a83f562362c462cbe8a94a',
    messagingSenderId: '305345322623',
    projectId: 'comunityler',
    storageBucket: 'comunityler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa9-LO6aWAKjHffcEwHtNYhETxTLPJ-Go',
    appId: '1:305345322623:ios:e196719fe6a19a09e8a94a',
    messagingSenderId: '305345322623',
    projectId: 'comunityler',
    storageBucket: 'comunityler.firebasestorage.app',
    iosBundleId: 'com.example.comunityler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa9-LO6aWAKjHffcEwHtNYhETxTLPJ-Go',
    appId: '1:305345322623:ios:e196719fe6a19a09e8a94a',
    messagingSenderId: '305345322623',
    projectId: 'comunityler',
    storageBucket: 'comunityler.firebasestorage.app',
    iosBundleId: 'com.example.comunityler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8nZUpgH3XToww0lczaDuzTDyH802Ffe8',
    appId: '1:305345322623:web:caf4e6ed6ec6d731e8a94a',
    messagingSenderId: '305345322623',
    projectId: 'comunityler',
    authDomain: 'comunityler.firebaseapp.com',
    storageBucket: 'comunityler.firebasestorage.app',
    measurementId: 'G-1MNMDEEVWR',
  );
}
